name: Pre-commit auto-update

on:
  workflow_call:
    inputs:
        path:
            type: string
            required: false
            description: "Path to the folder containing the package to update"
            default: "."

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-update:
    runs-on:
      group: default
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/setup-python@v2

      - name: Install sqlite3 and git
        run: |
          apt-get update
          apt-get install -y sqlite3 git

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - uses: actions/checkout@v4
        with:
          path: folder

      - name: Run pre-commit autoupdate on package
        run: |
          cd folder/${{ inputs.path }}
          pre-commit autoupdate

      - uses: peter-evans/create-pull-request@v3
        with:
          path: folder
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "Update pre-commit hooks"
          author: GitHub <noreply@github.com>
          labels: dependencies
          reviewers: ${{ github.actor }}
          delete-branch: true
          body: Update versions of pre-commit hooks to latest version.
