name: Test Cookiecutter template

on:
  workflow_call:
    inputs:
      config-file:
        required: false
        type: string
      python-version:
        required: false
        type: string


permissions: read-all

jobs:
  build:
    runs-on: self-hosted
    container:
      image: python:${{ inputs.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Install cookiecutter
        run: |
          pip install cookiecutter
      - name: Run cookiecutter with config file
        if: ${{ inputs.config-file }}
        run: cookiecutter . --no-input --config-file ${{ inputs.config-file }} 
      - name: Build Zephyr Application
        if: ${{ !inputs.config-file }}
        run: cookiecutter . --no-input
