name: Docker Compose Deploy

on:
  workflow_call:
    inputs:
      docker_host:
        type: string
        description: "Docker Host"
        required: false
        default: "tcp://192.168.73.6:2375"
      extra_args:
        type: string
        description: "Extra Arguments for up command"
        required: false
        default: ""
    secrets:
      env_variables:
        description: "Environment Variables"
        required: false

jobs:
  deploy:
    runs-on: sonu-github-arc
    environment: compose
    container:
      image: ubuntu:22.04

    steps:
      - name: Install sudo, curl, git, docker-compose
        run: apt update && apt install -y sudo curl git docker-compose

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker compose
        run: |
          ${{ secrets.env_variables }} DOCKER_HOST=${{ inputs.docker_host }} docker-compose up -d --build --force-recreate
