name: Lint Dockerfile, Build Docker image, Scout Quickview
on:
  workflow_call:
    inputs:
      dockerfile:
        type: string
        description: "Path to the Dockerfile"
        required: true
      ignore:
        type: string
        description: "Ignore rules"
        required: false
        default: "DL3008, DL3015"

jobs:
  check-dockerfile:
    runs-on: sonu-github-arc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: ${{ inputs.dockerfile }}
          failure-threshold: warning
          ignore: ${{ inputs.ignore }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t ${{ github.repository }}-ci -f ${{ inputs.dockerfile }} .
