name: Lint Dockerfile, Build Docker image, Scout Quickview
on:
  workflow_call:
    inputs:
      dockerfile:
        type: string
        description: "Path to the Dockerfile"
        required: true

jobs:
  check-dockerfile:
    runs-on: sonu-github-arc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: ${{ inputs.dockerfile }}
          failure-threshold: warning

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t ${{ github.repository }}-ci -f ${{ inputs.dockerfile }} .
