name: Publish to GHCR

on:
  workflow_call:
    inputs:
      Dockerfile:
        type: string
        description: "Path to the Dockerfile"
        required: false
        default: "."
      image_name:
        type: string
        description: "Name of the Docker image"
        required: false
        default: ${{ github.repository }}
      version:
        type: string
        description: "Version for the Docker image"
        required: false
        default: ""
      target:
        type: string
        description: "Target for the Dockerfile"
        required: false
        default: ""

    secrets:
      PAT:
        description: "Personal Access Token"
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ inputs.image_name }}

jobs:
  publish:
    runs-on: sonu-github-arc

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: If Tag Version
        id: tag
        run: |
          if [[ "${{ inputs.version }}" != '' ]]; then
            echo "::set-output name=tags::${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.version }}-${{ env.DOCKER_METADATA_OUTPUT_VERSION }}"
          else
            echo "::set-output name=tags::${{ steps.meta.outputs.tags }}"
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.Dockerfile}}
          push: true
          tags: ${{ steps.tag.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ inputs.target }}
