name: Lint Dockerfile, Build Docker image, Scout Quickview
on:
  workflow_call:
    inputs:
      dockerfile-path:
        type: string
        description: "Path to the Dockerfile"
        required: true
    secrets:
      DOCKERHUB_USERNAME:
        description: "Docker Hub username"
        required: true
      DOCKERHUB_TOKEN:
        description: "Docker Hub token"
        required: true

jobs:
  check-dockerfile:
    runs-on: sonu-github-arc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: ${{ inputs.dockerfile-path }}
          failure-threshold: warning

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t ${{ github.repository }}-ci -f ${{ inputs.dockerfile-path }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Scout Quickview
        run: docker scout quickview ${{ github.repository }}-ci
