name: Helm chart upgrade

on:
  workflow_call:
    inputs:
      release_name:
        type: string
        description: "Release Name"
        required: true
      namespace:
        type: string
        description: "Namespace"
        required: false
        default: default
      chart_path:
        type: string
        description: "Chart Path"
        required: false
        default: .
      values_file:
        type: string
        description: "Values File"
        required: false
        default: values.yaml
      extra_args:
        type: string
        description: "Extra Arguments"
        required: false
        default: ""
      submodules:
        type: string
        description: "Fetch submodules in checkout ? (true/recursive/false)"
        required: false
        default: "false"
      update:
        type: boolean
        description: "Update Helm"
        required: false
        default: false
      update_chart_name:
        type: string
        description: "Update Helm Chart Name"
        required: false
        default: ""
      update_chart_url:
        type: string
        description: "Update Helm Chart URL"
        required: false
        default: ""
    secrets:
      kubeconfig:
        description: "Kubeconfig"
        required: true

jobs:
  deployment:
    runs-on: "sonu-github-arc"
    container: "ubuntu:latest"
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y curl
      - uses: actions/checkout@v3
        with:
          submodules: ${{inputs.submodules}}
      - name: Install Charts
        if: ${{inputs.update}}
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm repo add ${{inputs.update_chart_name}} ${{inputs.update_chart_url}}
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          overrule_existing_kubeconfig: "true"
      - name: Update
        if: ${{inputs.update}}
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm repo add ${{inputs.update_chart_name}} ${{inputs.update_chart_url}}
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          overrule_existing_kubeconfig: "true"
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade ${{inputs.extra_args}} ${{inputs.release_name}} ${{inputs.chart_path}} --install --wait --atomic --namespace=${{inputs.namespace}} --values=${{inputs.values_file}} --force --create-namespace
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          overrule_existing_kubeconfig: "true"
