name: Helm chart upgrade

on:
  workflow_call:
    inputs:
      release_name:
        type: string
        description: "Release Name"
        required: true
      namespace:
        type: string
        description: "Namespace"
        required: false
        default: default
      chart_path:
        type: string
        description: "Chart Path"
        required: false
        default: .
      values_file:
        type: string
        description: "Values File"
        required: false
        default: values.yaml
    secrets:
      kubeconfig:
        description: "Kubeconfig"
        required: true

jobs:
  deployment:
    runs-on: "elegantencoder"
    container: "ubuntu:latest"
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y curl
      - uses: actions/checkout@v3
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade ${{inputs.release_name}} ${{inputs.chart_path}} --install --wait --atomic --namespace=${{inputs.namespace}} --values=${{inputs.values_file}}
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          overrule_existing_kubeconfig: "true"
