name: Run pre-commit

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: app/
      - uses: actions/setup-python@v3
      - name: ls
        run: ls -la
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: |
          cd app/ && 
          && pre-commit install \
          && pre-commit run --color=always --all-files
