name: Run pre-commit

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
    steps:
      - name: Install sqlite3
        run: apt-get update && apt-get install sqlite3 -y
      - name: Force install latest git
        run: |
          apt-get install -y software-properties-common \
          && apt-get update \
          && add-apt-repository -y ppa:git-core/ppa \
          && apt-get update \
          && apt-get install -y git
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - name: ls
        run: ls -la
      - uses: pre-commit/action@v3.0.0
