name: Run pre-commit

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: self-hosted
    container: kiwicom/pre-commit
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - name: Install git
        run: apt-get update && apt-get install -y git
      - uses: pre-commit/action@v3.0.0
