name: Run pre-commit

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: self-hosted
    container: ubuntu:22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - name: Install sqlite3
        run: apt-get update && apt-get install sqlite3
      - uses: pre-commit/action@v3.0.0
