name: Run pre-commit

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
    steps:
      - name: Install sqlite3 and git
        run: apt-get update && apt-get install -y sqlite3 && apt-get install -y git
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: |
          && pre-commit run --color=always --all-files
          
