name: Run pre-commit

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: sonu-github-arc
    container:
      image: ghcr.io/catie-aq/pre-commit_docker:latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: folder
      - name: Run pre-commit
        run: |
          cd folder/ \
          && pre-commit run --color=always --all-files
