name: Run pre-commit

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install sqlite3
        run: apt-get update && apt-get install sqlite3 -y
      - name: Install git
        run: apt-get update && apt-get install git -y
      - uses: pre-commit/action@v3.0.0
