name: Stress Test ARC Runners

on:
  workflow_dispatch:

jobs:
  stress:
    name: Stress Job
    runs-on: [sonu-github-arc]
    strategy:
      matrix:
        job_id:
          [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
          ]
      max-parallel: 40
    container:
      image: ubuntu:22.04
    steps:
      - name: Install stress
        run: |
          apt-get update && apt-get install -y stress
      - name: Print job info
        run: |
          echo "Running stress test job ${{ matrix.job_id }} on runner ${{ runner.name }}"
      - name: Simulate heavy load
        continue-on-error: true
        run: |
          echo "Starting CPU stress for 180s on 4 CPUs"
          timeout 180s stress --cpu 4
          echo "Done"
